name: Deploy to Kinsta

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Deploy to Kinsta
      uses: malwador/kinsta-deployment@main
      with:
        kinsta_host_ip: ${{ secrets.KINSTA_HOST_IP }}
        kinsta_username: ${{ secrets.KINSTA_USERNAME }}
        kinsta_password: ${{ secrets.KINSTA_PASSWORD }}
        kinsta_port: ${{ secrets.KINSTA_PORT }}
        target_path: ${{ secrets.KINSTA_TARGET_PATH }}
        exclude_patterns: '.git,.github,node_modules,.env,.DS_Store'
